### ISSUE TITLE
Storing images as fragments doesn't quite work

### ISSUE THREAD

**Issue by simonw** [agustif/llm-arxiv#2]
I tried this out just now and got an error about it exceeding the context length (even for GPT 4.1 with 1m tokens):

    llm -f arxiv:https://arxiv.org/abs/2310.06825 -m openai/gpt-4.1 summary

I managed to run it using [llm-echo](https://github.com/simonw/llm-echo) which lets me see exactly what was produced by the fragment without sending it to an LLM:

    llm -f arxiv:https://arxiv.org/abs/2310.06825 -m echo

I got this from `llm logs -s`:
```yaml
- model: echo
  datetime: '2025-05-04T17:33:53'
  conversation: 01jte5s40zqt5r7sn0dp9cje3s
  prompt_fragments:
  - b44203ad8d669237cbd161d89ede19b1e095afc97e984c264509dc596b704749
  - 1f9ed81b2a566c514374c3b094c275fa20832b86760b4a4279601da4d2eb6068
  - b742e42b93ef9f30b21b911e3a2f345fbd43eb17704096f0542d20a0bd72a939
  - 97c5f63b58d3cc5ef59a0a06a01dd80c9cc42adf55a9f83d9c265e5e7a330a86
  - 0eb4702eb2a1be7fc48f847f599b642c0d210d6286f0682c8f2769e3551dcfb5
  - a216280d9988bd66ee4f7a5231ee480e4b27512b9729698e4a9c3266483abea6
  - f7e90d579857690f598a1a01c2685cb308be39d166b6b48928170f0d7cd4149b
```
Running `llm fragments` showed me what was going on:

```yaml
- hash: 0eb4702eb2a1be7fc48f847f599b642c0d210d6286f0682c8f2769e3551dcfb5
  aliases: []
  datetime_utc: '2025-05-04 17:33:54'
  source: http://arxiv.org/abs/2310.06825v1/page_4_img_1.png
  content: iVBORw0KGgoAAAANSUhEUgAAKt0AAA3yCAIAAABDuOE9AAAACXBIWXMAAA7EAAAOxAGVKw4bACCceUlEQVR4nOzOMQEAMAwCM...
- hash: 1f9ed81b2a566c514374c3b094c275fa20832b86760b4a4279601da4d2eb6068
  aliases: []
  datetime_utc: '2025-05-04 17:33:54'
  source: http://arxiv.org/abs/2310.06825v1/page_1_img_1.jpeg
  content: /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYG...
- hash: 97c5f63b58d3cc5ef59a0a06a01dd80c9cc42adf55a9f83d9c265e5e7a330a86
  aliases: []
  datetime_utc: '2025-05-04 17:33:54'
  source: http://arxiv.org/abs/2310.06825v1/page_3_img_1.png
  content: iVBORw0KGgoAAAANSUhEUgAACfgAAAGSCAIAAAA65qVRAAAACXBIWXMAAA7EAAAOxAGVKw4bAACa2UlEQVR4nOzdeXwU9f3Hc...
- hash: a216280d9988bd66ee4f7a5231ee480e4b27512b9729698e4a9c3266483abea6
  aliases: []
  datetime_utc: '2025-05-04 17:33:54'
  source: http://arxiv.org/abs/2310.06825v1/page_5_img_1.png
  content: iVBORw0KGgoAAAANSUhEUgAAGL8AABEiCAIAAABU7C04AAAACXBIWXMAAA7EAAAOxAGVKw4bAArIZ0lEQVR4nOzde5CWdd0/8...
- hash: b44203ad8d669237cbd161d89ede19b1e095afc97e984c264509dc596b704749
  aliases: []
  datetime_utc: '2025-05-04 17:33:54'
  source: http://arxiv.org/abs/2310.06825v1
  content: |-
    Mistral 7B
    Albert Q. Jiang, Alexandre Sablayrolles, Arthur Mensch, Chris Bamford,
    Devendra Singh ...
- hash: b742e42b93ef9f30b21b911e3a2f345fbd43eb17704096f0542d20a0bd72a939
  aliases: []
  datetime_utc: '2025-05-04 17:33:54'
  source: http://arxiv.org/abs/2310.06825v1/page_2_img_1.png
  content: iVBORw0KGgoAAAANSUhEUgAACGQAAAMgCAIAAADgYrGhAAAACXBIWXMAAA7EAAAOxAGVKw4bAAILlElEQVR4nOzdB1wUR/8/c...
- hash: f7e90d579857690f598a1a01c2685cb308be39d166b6b48928170f0d7cd4149b
  aliases: []
  datetime_utc: '2025-05-04 17:33:54'
  source: http://arxiv.org/abs/2310.06825v1/page_7_img_1.png
  content: iVBORw0KGgoAAAANSUhEUgAABngAAAn4CAIAAADVmzrNAAAACXBIWXMAAA7EAAAOxAGVKw4bAAb3A0lEQVR4nOzdCZBcZYIf+...
```
Those images are being stored and included as base64 strings directly in the prompt. That's not going to work for most models, including the OpenAI ones.

The solution is going to need a change to LLM core itself - issue here:
- https://github.com/simonw/llm/issues/972
